### PR TITLE
Fix #265 Recover from Lambda timeouts

### LINKED ISSUE #265: "PHP-FPM has already been started" on any Symfony PHP call making a PDO connection
Not sure this is a specific, identifiable issue in itself, whether it relates to any other FPM timeout / RDS 
issues currently ongoing, or whether it can shed light on any of these. Please let me know if I can usefully provide more info or try anything like a new layer version.

I note (relating also to twitter discussions with @nealio82) that there are two security models for RDS/VPC interaction, depending on how long the relevant AWS account has been using RDS for (note: not just how old the AWS account is): https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.FindDefaultVPC.html

My specific error is as follows:

From a single API call within a Symfony 3.4 app, itself making single PDO connection to a mysql instance inside a VPC. App returns with `{"message": "Internal server error"}`

RDS has: Public accessibility: Yes

The RDS instance is accessible with the same credentials from a remote mysql client.

I can't figure out how I'd directly tell if the MySQL connection is actually being made by the Lambda, or if it's just timing out.

Logs from CloudWatch 

```
[11-Mar-2019 19:06:07] NOTICE: fpm is running, pid 8
[11-Mar-2019 19:06:07] NOTICE: ready to handle connections
START RequestId: 30c32c12-bbbe-464f-ae55-9597a36fa0ea Version: $LATEST
END RequestId: 30c32c12-bbbe-464f-ae55-9597a36fa0ea
REPORT RequestId: 30c32c12-bbbe-464f-ae55-9597a36fa0ea	Init Duration: 277.33 ms	Duration: 30030.15 ms	Billed Duration: 30400 ms Memory Size: 1024 MB	Max Memory Used: 122 MB	
2019-03-11T19:06:37.178Z 30c32c12-bbbe-464f-ae55-9597a36fa0ea Task timed out after 30.03 seconds

PHP Fatal error: Uncaught Exception: PHP-FPM has already been started, aborting in /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php:50
Stack trace:
#0 /opt/bootstrap(22): Bref\Runtime\PhpFpm->start()
#1 {main}
thrown in /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php on line 50

Fatal error: Uncaught Exception: PHP-FPM has already been started, aborting in /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php:50
Stack trace:
#0 /opt/bootstrap(22): Bref\Runtime\PhpFpm->start()
#1 {main}
thrown in /var/task/vendor/mnapoli/bref/src/Runtime/PhpFpm.php on line 50
```

Template file:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Resources:
    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'com-weightinwhales-lambda-php'
            Description: ''
            CodeUri: .
            Handler: web/app.php
            Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
            MemorySize: 1024 # The memory size is related to the pricing and CPU power
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:eu-west-1:209497400698:layer:php-73-fpm:2'
            Events:
                # The function will match all HTTP URLs
                HttpRoot:
                    Type: Api
                    Properties:
                        Path: /
                        Method: ANY
                HttpSubPaths:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY

    AssetsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: 'assets.weightinwhales.com'
            AccessControl: PublicRead
            WebsiteConfiguration:
                IndexDocument: index.html
            CorsConfiguration:
                CorsRules:
                    - AllowedMethods:
                        - GET
                      AllowedOrigins:
                        - !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
                        - http://127.0.0.1:3000

# Outputs show up in the CloudFormation dashboard
Outputs:
    DemoHttpApi:
        Description: 'URL of our function in the *Prod* environment'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
```

### PR DESCRIPTION
**Pull request by mnapoli**
In #257 I added some code to support and recover from PHP-FPM timeouts.

However we still have problems with Lambda timeouts (#265): those timeouts cause AWS Lambda to kill our `bootstrap` process and restart it.

I added some code to handle all scenarios I could think of: whether PHP-FPM was still running or not. From what I've seen in my tests Lambda correctly kills the `bootstrap` process but it kills PHP-FPM properly as well (see https://github.com/mnapoli/bref/issues/265#issuecomment-473368865). That's good, in those cases Bref will simply restart PHP-FPM and be good to go.

I cannot add regression tests because SAM recreates a new instance on every invocation, so it's impossible to keep a broken instance around. I tested directly on AWS Lambda.

This change requires a new layer version because `php-fpm.conf` is modified.

### CODE REVIEW

File: demo/http.php [hunk 1]
```diff
@@ -1,20 +1,9 @@
...
-$slim->get('/json', function (ServerRequestInterface $request, ResponseInterface $response) {
-    $response->getBody()->write(json_encode(['hello' => 'json']));
-    $response = $response->withHeader('Content-Type', 'application/json');
-    return $response;
-});
+if (isset($_GET['sleep'])) {
+    sleep(10);
+}
 
-$slim->run();
```
Comment (mnapoli) [inline demo/http.php]: Slim wasn't installed anymore. We don't need it for the demo.

File: runtime/php/layers/fpm/php-fpm.conf [hunk 2]
```diff
@@ -1,5 +1,6 @@
 ; Logging anywhere on disk doesn't make sense on lambda since instances are ephemeral
 error_log = /dev/null
+pid = /tmp/.bref/php-fpm.pid
```
Comment (mnapoli) [inline runtime/php/layers/fpm/php-fpm.conf]: This lets us keep track of the PID to check if PHP-FPM is still running or not.

**Comment by cosmok** [comment]
Hi @mnapoli,

Is the new layer released? I am using bref:layer.php-72-fpm with the latest bref package from composer and I can see these errors.
